[project]
name = "fastdaimacodeassist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "tree-sitter-languages>=1.10.2",
    "tree-sitter-python>=0.23.4",
    "tree-sitter==0.21.3",
]
